name:                haskell-yaml
version:             0.1.0.0
github:              "fersilva16/haskell-yaml"
license:             MIT
author:              "Fernando Silva"
maintainer:          "hello@fersilva.dev"
copyright:           "2022 Fernando Silva"
description:         Please see the README on GitHub at <https://github.com/fersilva16/haskell-yaml#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  haskell-yaml-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  haskell-yaml-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
